# Project information
site_name: BURSTPAY Mobile Wallet
site_description: Documentation for the BURSTPAY Mobile Wallet
site_author: iHashing
site_url: https://github.com/ihashing/BURSTPAY-mobile

# Repository
repo_name: BURSTPAY-mobile-doc
repo_url: https://github.com/ihashing/BURSTPAY-mobile-doc

# Theme
theme:
  name: 'material'
  favicon: assets/img/favicon.ico
  logo: assets/img/logo.png
  feature:
    tabs: false
  palette:
    primary: indigo
    accent: indigo

# Options
extra:
  social:
    - type: github-alt
      link: https://github.com/ihashing
    - type: twitter
      link: https://twitter.com/BURSTPAY

# Page tree
pages:
  - Documentation: index.md
  - Wallet:
      - Create Account: wallet/create.md
      - Import Account: wallet/import.md
      - Activate Account: wallet/activate.md
      - Switch Account: wallet/switch.md
      - Remove Account: wallet/remove.md
  - PIN Code: pin.md
  - Send Burstcoins: send.md
  - Transaction History: transactions.md
  - Privacy Policy: privacy_policy.md

# Google Analytics
google_analytics:
  - UA-xxxxxxxxx-x
  - auto
